# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Herder < Formula
  desc "A TUI process orchestrator for development environments"
  homepage "https://github.com/frontendtony/shepherd"
  version "0.1.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/frontendtony/shepherd/releases/download/v0.1.3/shepherd_darwin_amd64.tar.gz"
      sha256 "a456655205a222e9275144641f48b0e78b6f50ed7874923ce1202efc35815506"

      def install
        bin.install "shepherd"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/frontendtony/shepherd/releases/download/v0.1.3/shepherd_darwin_arm64.tar.gz"
      sha256 "048e2abf513656b57c6853ece18b04ee3806da495fbc6a176a47881f8f7cdb28"

      def install
        bin.install "shepherd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/frontendtony/shepherd/releases/download/v0.1.3/shepherd_linux_amd64.tar.gz"
      sha256 "efd5a9dbdf71d2302f3bb9467037a42df74ac9c9b86898951cfd4b43b263cbb2"
      def install
        bin.install "shepherd"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/frontendtony/shepherd/releases/download/v0.1.3/shepherd_linux_arm64.tar.gz"
      sha256 "5d776ff35d373a2913ca4a51c88eed2c4b16dcacf42a4a555cb9f80770b5d921"
      def install
        bin.install "shepherd"
      end
    end
  end

  test do
    system "#{bin}/shepherd", "--help"
  end
end
