# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Shepherd < Formula
  desc "A TUI process orchestrator for development environments"
  homepage "https://github.com/frontendtony/shepherd"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/frontendtony/shepherd/releases/download/v0.1.2/shepherd_darwin_amd64.tar.gz"
      sha256 "bbfcfb424c9ad11b499915a58d5dbbf548e32563d5e823fb5c0c2463dcd25b10"

      def install
        bin.install "shepherd"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/frontendtony/shepherd/releases/download/v0.1.2/shepherd_darwin_arm64.tar.gz"
      sha256 "674a3a27e5a17ff6b6b91795d2fd05a4621d5372ce9260a0edeecfb4e343e871"

      def install
        bin.install "shepherd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/frontendtony/shepherd/releases/download/v0.1.2/shepherd_linux_amd64.tar.gz"
      sha256 "eddba7bfc40833789e6736f81b1040210958baa0b57d2e01b3f3cf746cc05dc3"
      def install
        bin.install "shepherd"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/frontendtony/shepherd/releases/download/v0.1.2/shepherd_linux_arm64.tar.gz"
      sha256 "e30002588adb222832c651db9b5409b6824ed9a1b3cccd6340f7e4e3274440bd"
      def install
        bin.install "shepherd"
      end
    end
  end

  test do
    system "#{bin}/shepherd", "--help"
  end
end
