# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Shepherd < Formula
  desc "A TUI process orchestrator for development environments"
  homepage "https://github.com/frontendtony/shepherd"
  version "0.1.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/frontendtony/shepherd/releases/download/v0.1.4/shepherd_darwin_amd64.tar.gz"
      sha256 "59621e12fb62588893e956c35c13c216806bcd66fab44c9c92ca210e0cf2ea5a"

      def install
        bin.install "shepherd"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/frontendtony/shepherd/releases/download/v0.1.4/shepherd_darwin_arm64.tar.gz"
      sha256 "cf88def22a0d7f310cd2114241a52b2897348012799cb54dbc81a888a01985e7"

      def install
        bin.install "shepherd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/frontendtony/shepherd/releases/download/v0.1.4/shepherd_linux_amd64.tar.gz"
      sha256 "2e48be7a7ab8d68a53edfd331f6dce88eb9d041f3fd1af4d915e781ac7fceec8"
      def install
        bin.install "shepherd"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/frontendtony/shepherd/releases/download/v0.1.4/shepherd_linux_arm64.tar.gz"
      sha256 "c159ba070502492622f9c1fc38e0e2254cd7792a4b7f01de5aa82d931f90a021"
      def install
        bin.install "shepherd"
      end
    end
  end

  test do
    system "#{bin}/shepherd", "--help"
  end
end
