# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Shepherd < Formula
  desc "A TUI process orchestrator for development environments"
  homepage "https://github.com/frontendtony/shepherd"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/frontendtony/shepherd/releases/download/v0.1.1/shepherd_darwin_amd64.tar.gz"
      sha256 "396008ea933edf42f32b6be8e002decb60b76369895f6620909a886a5e71840d"

      def install
        bin.install "shepherd"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/frontendtony/shepherd/releases/download/v0.1.1/shepherd_darwin_arm64.tar.gz"
      sha256 "7cfc64c72198cccadd6761c259f970b4047975c0c8f75ba6ead337e3f546b6db"

      def install
        bin.install "shepherd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/frontendtony/shepherd/releases/download/v0.1.1/shepherd_linux_amd64.tar.gz"
      sha256 "4be8d5625ba900b8a2a56397703e2e08403f15541cbc9013eac04d0657614afe"
      def install
        bin.install "shepherd"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/frontendtony/shepherd/releases/download/v0.1.1/shepherd_linux_arm64.tar.gz"
      sha256 "2c62b459d13a959dfd7715192d5380ed496af6bcd851d21d6ab604f5e6fa2ebf"
      def install
        bin.install "shepherd"
      end
    end
  end

  test do
    system "#{bin}/shepherd", "--help"
  end
end
